### ISSUE TITLE
`function-args.el` should require `swiper`

### ISSUE THREAD

**Issue by dholm** [abo-abo/function-args#24]
Functions like `moo-complete` require functions that are defined in `ivy`/`swiper` but `function-args.el` doesn't have a `require` for this module.  This is what happens when calling `moo-complete` without specifically requiring `swiper` first:

    moo-select-candidate: Symbol's function definition is void: ivy-read

**Comment by abo-abo** [comment]
Thanks for noticing. Should work now.
