### ISSUE TITLE
fa-show overlay display issue

### ISSUE THREAD

**Issue by ryan-maus** [abo-abo/function-args#25]
I'm following the http://tuhdo.github.io/c-ide.html tutorial; I'm at the function-args part and I'm having some issues with getting fa-show to display properly.

The overlay hint is just one line directly above the first function argument, and its a garbled mess of letters (looks like all options are just rendered in the same small space, instead of being spread out in the overlay menu).

I'm using a fresh install of Emacs 24.5, no x toolkit (so, terminal only) with GNU Global 6.4.  I've not really modified the 'demo' configuration from that tutorial aside from a few keybindings (nothing that should cause a visual display issue like this).

**Comment by abo-abo** [comment]
Just checked: works fine in graphical / inside Gnome terminal / inside tty. Please post a screenshot of your bug, with `emacs -Q`.

**Comment by ryan-maus** [comment]
![fa-mode-capture](https://cloud.githubusercontent.com/assets/302280/7972266/b7e4c010-0a10-11e5-890b-2fae3969f0f6.PNG)

I'm relatively new with emacs, I'm not sure what you mean by emacs -Q (this mode disables all of the installed packages and I can't replicate the issue as there is no function-args-mode at all).

**Comment by ryan-maus** [comment]
Ok, looks like just the coloring is way off, the actual text is correct for the hint overlay.  Additionally, somewhere the keybinds for fa-idx-cycle-up and fa-idx-cycle-down were overridden which explains why the hint navigation wasn't working.

Any tips for getting the coloring to work a little better with solarized-dark?

**Comment by abo-abo** [comment]
Updated the faces:

![function-args-solarized-dark](https://cloud.githubusercontent.com/assets/2937359/7978964/690d9fd0-0a9b-11e5-9bd3-75193e12279b.png)

**Comment by abo-abo** [comment]
> Additionally, somewhere the keybinds for fa-idx-cycle-up and fa-idx-cycle-down were overridden which explains why the hint navigation wasn't working.

The keybinds should work if `function-args-mode` is on. You can turn it on with <kbd>M-x</kbd>.  To have it automatically, add this to `~/.emacs`:

    (fa-config-default)
