### ISSUE TITLE
show also function description with M-i

### ISSUE THREAD

**Issue by lin2280778** [abo-abo/function-args#26]
Hi abo-abo

I would like to ask you that is it possible to show also @param and @return information insert by moo-doxygen when active M-i.  example

@param variableInput : input data
@param variableoutput: output data
@return true/false
(int variableinput, int variableoutput): int

include doxygen comment  @param and @return but without stars \/* ****

thank you

**Comment by abo-abo** [comment]
You mean if a function has a (Doxygen) comment before its definition, add that comment on top of <kbd>M-i</kbd>?

It's not straightforward to extract the comment, and I'm not using Doxygen currently, so I'll need a test file from you.

**Comment by lin2280778** [comment]
thank you for replying  and yes, it is like what you said. 

for example, in test.c :
=================================================
#include <math.h>
#include "test.h"
#include <stdio.h>


/**
 * Here is func2  description 
 *
 * @param a : description input a 
 * @param b : description input b
 * @return (a+b) : description output 
 */
int func2(float a, bool b){
  print("haha");
  return (a+b)
}

int main()
{
func2()
}

return 0;
===============================================

now, I don't know what arguments to write in func2(), then I press M-i, I hope to obtain like this.

  @param a : description input a 
  @param b : description input b
  @return (a+b) : description output 
 (float a, bool b): int

it's amazing to obtain the explication of arguments.   

Thank you

**Comment by lin2280778** [comment]
sorry, there is not point before @param, that was *, gitpub changed * to point....

**Comment by abo-abo** [comment]
> sorry, there is not point before @param, that was *, gitpub changed * to point....

You should edit your message to indent the source blocks with 4 spaces. That will make them look nice.
Or you can use the fence syntax:

    ```c++
    int main() {
    return 0;
    }
    ```

For more info on Markdown, which Github uses as markup, see: http://daringfireball.net/projects/markdown/syntax.

**Comment by lin2280778** [comment]
Thank you abo-abo, so you understand what feature I want ?   is that possible?  
    #include <math.h>
#include "test.h"
#include <stdio.h>


/**
 * Here is func2  description 
 *
 * @param a : description input a 
 * @param b : description input b
 * @return (a+b) : description output 
 */
int func2(float a, bool b){
  print("haha");
  return (a+b)
}
    
here is the code

**Comment by abo-abo** [comment]
Thanks, it should now be possible to see comments if you set `fa-do-comments`:

![fa-do-comments](https://cloud.githubusercontent.com/assets/2937359/8476213/85361568-20bf-11e5-9d0e-cdcf28ce3506.png)
