### ISSUE TITLE
bugs of "moo-select-method" when using "helm" to narrow down candidates

### ISSUE THREAD

**Issue by oracleyue** [abo-abo/function-args#27]
Could you check and confirm the following bug? Any ideas to fix it? Thanks a lot!!
1. When "moo-select-method" is "ivy", it shows candidates and narrows down to the right one correctly, as below:
   <img width="723" alt="screen shot 2015-08-17 at 07 58 50" src="https://cloud.githubusercontent.com/assets/5046605/9298935/ed1230ac-44b6-11e5-81f9-d50182628e34.png">
2. When "moo-select-method" is "helm", it shows candidates. However, once I typed in any letters to narrow down the candidates, I got errors, as illustrated below.
   <img width="726" alt="screen shot 2015-08-17 at 08 00 52" src="https://cloud.githubusercontent.com/assets/5046605/9298896/b756827e-44b6-11e5-9a2b-657d07a4dea2.png">
   <img width="726" alt="screen shot 2015-08-17 at 08 01 03" src="https://cloud.githubusercontent.com/assets/5046605/9298937/eeb00a2e-44b6-11e5-9d37-72f38db5f485.png">
   (There is a pretty strange thing happened. When I tested `std::string str; str.`, it still works well. However, when I tested others, e.g. `std::ostream out; out.` or others, the error reported.
   **Is it possible that it is actually a bug of helm, instead of function-args?**)

Versions:
Emacs 24.4.1
Helm 2015.08.15.740
Function-args 20150731

Configurations:

``` elisp
       (require 'function-args)
       ;; enable case-insensitive searching
       (set-default 'semantic-case-fold t)
       ;; set selection interface
       (setq moo-select-method 'helm)  ;; ivy
       ;; enable function-args
       (add-hook 'c-mode-hook 'fa-config-default)
       (add-hook 'c++-mode-hook 'fa-config-default)
```

**Comment by abo-abo** [comment]
This is due to a change in helm. It supported alists as sources before, now it doesn't.  It would require more work than I'd like to make helm work without alists. I suggest to wait, maybe it will come back. An older version of helm should work fine as well.

**Comment by oracleyue** [comment]
@abo-abo Many thanks for your prompt response! Hope it would be fixed later. Thanks for your confirmation

**Comment by oracleyue** [comment]
@abo-abo FYI, according to https://github.com/emacs-helm/helm/issues/1133#issuecomment-132192556, the developer of `helm` claimed that this feature hasn't been removed. 
Could you locate new reasons to the bug later when you got time? Many thanks!

**Comment by oracleyue** [comment]
BTW, in your sample snapshot in Readme.md, the `moo-complete` completion windows can be at right-hand side. The default is to split window vertically. I briefly searched your code, and failed to find any configurations to make it split horizontally. Is it depending on helm's split-window setting? If it were, then that's fine, it is just another tiny and indifferent bug due to changes in helm (since I have tried changing the default split-window type of helm)

**Comment by abo-abo** [comment]
OK, I'll check again the alist thing. The window splitting config is:

    (setq helm-split-window-default-side 'right)

**Comment by oracleyue** [comment]
@abo-abo Hi, have you removed the support helm from the latest version? I updated it recently and found that, no matter what `moo-select-method` is set to, it always trigger **ivy** to show the list. (I know the bug I reported before. Just check if you removed the support of helm directly, or it's my setting problem.) Thanks!

**Comment by abo-abo** [comment]
Helm support wasn't removed (`moo-jump-directory` still uses it), but it has heavily deteriorated.
The new function rewrites just use `ivy-read` now. I wouldn't mind making the completion generic again, but I've got other things to invest my time in. PRs welcome.

**Comment by oracleyue** [comment]
@abo-abo Thanks! I may take a look at it, and see if I am able to fix it. I haven't yet have experience on developing any modes in elisp. :) Thanks a lot for your minor-mode! It's still pretty helpful~
