### ISSUE TITLE
fa-show reports 'Wrong type argument'?

### ISSUE THREAD

**Issue by Zhro** [abo-abo/function-args#28]
GNU Emacs 24.5.1 in `-nw` terminal mode.

Slimmed .emacs:

    (require 'cedet)

    (setq semanticdb-default-save-directory "~/.semanticdb/")

    (semantic-mode 1)

    (add-to-list 'load-path "~/.emacs.d/function-args")
    (add-to-list 'load-path "~/.emacs.d/swiper") ;; function-args dependency
    (require 'function-args)
    (fa-config-default)

Using the collowing code:
    
    class Rectangle {
      int width;
      int height;

    public:
      void set_values(int, int);
    };

    int main () {
      Rectangle rect;

      rect.set_values(

      return 0;
    }

With the cursor set to the right of `rect.set_values(`, I activate `fa-show` and get the following error in the minibuffer:

`Wrong type argument:  integerp, nil`

**Comment by abo-abo** [comment]
Could be a problem with semantic parser. Try M-x semantic-force-refresh.

**Comment by Zhro** [comment]
Spectacularly fast response. You can close this as I'm new to function-args and was hitting `M-u` to invoke fa-abort instead of `M-i` for fa-show.

**Comment by abo-abo** [comment]
Lol.
