### ISSUE TITLE
Error when executing fa-jump or fa-show

### ISSUE THREAD

**Issue by emacsuser123** [abo-abo/function-args#34]
Hi.

I'm doing some development on C language, ubuntu 14.04.

I'm getting the following error whenever I try to run fa-jump or fa-show:

_Wrong type argument: stringp, (((0) "__FILE"))_

Other FA functions, like, moo-jump-local run OK, without any problem.

My emacs version is:
24.5.1, x64

and I'm using the latest version of function-args from Melpa.

Any idea?

Thanks a lot.
-Bob

**Comment by abo-abo** [comment]
The bug seems to be related to you source code. Since I just tested `fa-jump` and `fa-show` on `putchar` and it works fine.

Give me a minimal example of source code that reproduces the bug, maybe I can fix it.

**Comment by emacsuser123** [comment]
Hi.

The problem can be reproduced easily just by using this minimal example:

#include <stdio.h>
#include <stdlib.h>

_int main(int argc, char **argv)
{
  int r = 5; 
  printf("hello: %d\n", r);
  exit(0);
}_

Maybe the problem arises when interacting with other features on my emacs ini file.

The function-args part on my ini file just does the following:
  _(fa-config-default)

Thanks.
-Bob
  (set-default 'semantic-case-fold t)_

**Comment by abo-abo** [comment]
Some of your code got garbled. This code works fine for me:

```c
#include <stdio.h>

int main(int argc, char *argv[]) {
  int r = 5;
  printf ("hello: %d\n", r);
  return 0;
}
```

When I move point to `printf` and call `fa-show` the proper hint is displayed. And when I can `fa-jump` the correct jump is made.

Consider removing `~/.emacs.d/semanticdb` and restarting Emacs, that might help.

**Comment by emacsuser123** [comment]
Thanks.

I've followed your recommendation of removing semanticdb directory and now it seems to be working fine.

P.S. Closing this issue now...

Regards.
