### ISSUE TITLE
Error: unexpected tag when trying to jump to a certain function in the list displayed by moo-jump-local

### ISSUE THREAD

**Issue by emacsuser123** [abo-abo/function-args#35]
Hi.

I'm getting unexpected tag error whenever I try to jump to a certain function displayed by moo-jump-local.

I have tried to regenerate the tags, as well as recreate the semanticdb, but the result is the same.

Any idea why this is happening?

I'm using emacs 24.5.1, 64bits, on a linux machine.

Below there is a backtrace included, where you can see the problem.

thanks.
-Bob

----------------------------------------------------------------------------------------------------

> Debugger

 

> entered--entering a function:
> * format("Unexpected tag: %S" (#("static inline uint16_t my_function (unsigned char *data, uint16_t max);                                                                                                           app.c" 0 14 (face font-lock-keyword-face) 14 22 (face font-lock-type-face) 23 47 (face font-lock-function-name-face) 49 62 (face font-lock-type-face) 70 78 (face font-lock-type-face)) "my_function" function (:typemodifiers ("static" "inline") :arguments (("data" variable (:pointer 1 :type "unsigned char") (reparse-symbol arg-sub-list) #<overlay from 2620 to 2640 in app.c>) ("max" variable (:type ("uint16_t" type (:type "class") nil nil)) (reparse-symbol arg-sub-list) #<overlay from 2641 to 2654 in app.c>)) :type ("uint16_t" type (:type "class") nil nil) :truefile "/home/bob/git/app/src/app.c") nil #<overlay from 2572 to 3191 in app.c>))
> * apply(format ("Unexpected tag: %S" (#("static inline uint16_t my_function (unsigned char *data, uint16_t max);                                                                                                           app.c" 0 14 (face font-lock-keyword-face) 14 22 (face font-lock-type-face) 23 47 (face font-lock-function-name-face) 49 62 (face font-lock-type-face) 70 78 (face font-lock-type-face)) "my_function" function (:typemodifiers ("static" "inline") :arguments (("data" variable (:pointer 1 :type "unsigned char") (reparse-symbol arg-sub-list) #<overlay from 2620 to 2640 in app.c>) ("max" variable (:type ("uint16_t" type (:type "class") nil nil)) (reparse-symbol arg-sub-list) #<overlay from 2641 to 2654 in app.c>)) :type ("uint16_t" type (:type "class") nil nil) :truefile "/home/bob/git/app/src/app.c") nil #<overlay from 2572 to 3191 in app.c>)))
> * error("Unexpected tag: %S" (#("static inline uint16_t my_function (unsigned char *data, uint16_t max);                                                                                                           app.c" 0 14 (face font-lock-keyword-face) 14 22 (face font-lock-type-face) 23 47 (face font-lock-function-name-face) 49 62 (face font-lock-type-face) 70 78 (face font-lock-type-face)) "my_function" function (:typemodifiers ("static" "inline") :arguments (("data" variable (:pointer 1 :type "unsigned char") (reparse-symbol arg-sub-list) #<overlay from 2620 to 2640 in app.c>) ("max" variable (:type ("uint16_t" type (:type "class") nil nil)) (reparse-symbol arg-sub-list) #<overlay from 2641 to 2654 in app.c>)) :type ("uint16_t" type (:type "class") nil nil) :truefile "/home/bob/git/app/src/app.c") nil #<overlay from 2572 to 3191 in app.c>))
> * #[257 "\306\307 \310\"\203

**Comment by abo-abo** [comment]
Should work now. Thanks.

**Comment by emacsuser123** [comment]
It works ok now.

thanks a ton.
