### ISSUE TITLE
Filter tags in moo-jump-local

### ISSUE THREAD

**Issue by gperaza** [abo-abo/function-args#36]
I really like this package, but I was wondering is there is a way to do the following things:

Is there a way to filter tags by type in moo-jump-local? In helm-semantic this can be done by setting the tag format function to semantic-format-tag-summarize, this shows the tag type (functions, variables, dependencies).

Also, is there a follow mode? Sometimes I like to preview where I'm going to jump before exiting moo-jump-local.

Thanks.

**Comment by abo-abo** [comment]
> Is there a way to filter tags by type in moo-jump-local?

You can filter some things, like includes, requires and provides by entering the text. I don't see much use in filtering by type instead of by name.

> Also, is there a follow mode? Sometimes I like to preview where I'm going to jump before exiting moo-jump-local.

Of course. Just press <kbd>C-M-n</kbd> and <kbd>C-M-p</kbd>. Or <kbd>C-o jjkkkjk</kbd>.
