### ISSUE TITLE
completion not working

### ISSUE THREAD

**Issue by cneira** [abo-abo/function-args#37]
```c++
using namespace std;

struct Foo {
  int field_1;
  int another_field_2;
};
`
void one()
{
  Foo foo;
  foo.      // <-- does not brings up helm complete , just a minibuffer menu that returns (int field_1, int another_field_2 )

}
```
int main ()
{
  std::vector < int > v;
  std::string s;
  std::map <int,int> m;
     
 v.     //<-- semantic-analyze-possible-completions-default: Cannot find types for ‘std::vector v’
m.    //<--- semantic-analyze-possible-completions-default: Cannot find types for ‘std::map m’
   
}
```

**Comment by abo-abo** [comment]
All 3 cases work fine for me (provided I `#include <vector>, #include <map>`). Simply call `moo-complete`.

Alternatively, if you want <kbd>C-M-i</kbd> (`complete-symbol`) to work, here's the config:

```elisp
(add-hook 'c-mode-common-hook 'ora-c-common-hook)
(defun ora-c-common-hook ()
  (add-hook 'completion-at-point-functions 'moo-completion-at-point))
```

**Comment by cneira** [comment]
Hi, this simple test is not working for me.  
#include <string>
#include <vector>

int main() {

  std::string s;
  std::vector <int> v;
  v.  --> no matches found 
}

I'm on windows using the following system includes

(semantic-add-system-include "C:/cygwin64/lib/gcc/x86_64-w64mingw32/4.9.2/include/" 'c++-mode)
