### ISSUE TITLE
Missing explicit declaration of dependency ivy

### ISSUE THREAD

**Issue by p3r7** [abo-abo/function-args#39]
After updating via default package manager, I get the following error on emacs start:
```
Debugger entered--Lisp error: (void-function ivy-set-actions)
  ivy-set-actions(moo-select-candidate (("i" moo-action-implement "implement")))
```

I assume that this is due to missing dependency swiper/ivy on my system.

Maybe all there is to do is to make this dependency explicit ?

**Comment by abo-abo** [comment]
Thanks, fixed.

**Comment by dholm** [comment]
I still have this issue with `function-args` 20170822.1002.

In my `cc-mode` configuration I have the following code:
```
(use-package function-args
    :pin "MELPA"
    :diminish function-args-mode
    :config
    (fa-config-default)
```

This triggers the following error:

```
Error (use-package): cc-mode :config: Symbol’s function definition is void: ivy-set-actions
```
